import Route from '@ioc:Adonis/Core/Route'

Route.group(() => {
  Route.get('/new', 'DefectsController.create').as('create').middleware(['auth'])
  Route.post('/new', 'DefectsController.store').as('store').middleware(['auth'])
  Route.get('/show/:id', 'DefectsController.show').as('show')
  Route.get('/edit/:id', 'DefectsController.edit').as('edit').middleware(['auth'])
  Route.post('/edit/:id', 'DefectsController.update').as('update').middleware(['auth'])
  Route.get('/delete/:id', 'DefectsController.destroy').as('destroy')
  Route.get('/edit-deadline/:id', 'DefectsController.editDeadline')
    .as('edit.deadline')
    .middleware(['auth'])
  Route.post('/edit-deadline/:id', 'DefectsController.updateDeadline')
    .as('update.deadline')
    .middleware(['auth'])
  Route.get('/checkup-create/:idDefect', 'DefectsController.checkupCreate')
    .as('checkup-create')
    .middleware(['auth'])
  Route.post('/checkup-create/:idDefect', 'DefectsController.checkupStore')
    .as('checkup.store')
    .middleware(['auth'])
  Route.get('/delete-checkup/:idInterCheck', 'DefectsController.checkupDestroy')
    .as('checkup.destroy')
    .middleware(['auth'])
  Route.get('/close-defect/:idDefect', 'DefectsController.closeDefectCreate')
    .as('close.create')
    .middleware(['auth'])
  Route.post('/close-defect/:idDefect', 'DefectsController.closeDefectStore')
    .as('close.store')
    .middleware(['auth'])
})
  .prefix('/defects')
  .as('defects')
